### ISSUE TITLE
Форум упал

### ISSUE THREAD

**Issue by Izvekov** [WendyH/PHP-Scripts#1]
Других контактов у меня нет,  форум упал - печалька.

**Comment by WendyH** [comment]
Спасибо, починил.

**Comment by Izvekov** [comment]
Опять упал. Что-то с mysql опять :(

**Comment by Izvekov** [comment]
Опять упал форум, Unable to connect to MySQL and select database.
MySQL reported: No such file or directory. Почините пожалуйста.

**Comment by Izvekov** [comment]
В очередной раз mysql на форуме вышел из строя. Восстановите работу пожалуйста. Спасибо за реанимацию ключей.
