### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Numenorean** [WendyH/PHP-Scripts#2]
Пытаюсь получить ссылки, но вылазет такая ошибка 
Warning: file_get_contents(/assets/video-0c2f2b38bab325e4c63702bd6818ff9f50187725d5973ce722ac0ba3a3501ff2.js): failed to open stream: No such file or directory in /home/j/j92063q2/view/public_html/moonwalk.php on line 144 Notice: Undefined variable: http_response_header in /home/j/j92063q2/view/public_html/moonwalk.php on line 146 Warning: Invalid argument supplied for foreach() in /home/j/j92063q2/view/public_html/moonwalk.php on line 146 Warning: file_get_contents(/vs): failed to open stream: No such file or directory in /home/j/j92063q2/view/public_html/moonwalk.php on line 144 Notice: Undefined variable: http_response_header in /home/j/j92063q2/view/public_html/moonwalk.php on line 146 Warning: Invalid argument supplied for foreach() in /home/j/j92063q2/view/public_html/moonwalk.php on line 146 Warning: file_get_contents(/vs): failed to open stream: No such file or directory in /home/j/j92063q2/view/public_html/moonwalk.php on line 144 Notice: Undefined variable: http_response_header in /home/j/j92063q2/view/public_html/moonwalk.php on line 146 Warning: Invalid argument supplied for foreach() in /home/j/j92063q2/view/public_html/moonwalk.php on line 146
Ссылка, с которой пытаюсь получить m3u8: http://moonwalk.cc/video/dd7db41af0a6adc86a44cad9f4ef3474/iframe

**Comment by vitnets** [comment]
А Вас не смущает путь? file_get_contents(/assets/....)

Попробуйте закомментировать вот это: $urlBase = $options["proto"].$options["host"];
